### ISSUE TITLE
Experiment on full set of `iapp_wiki_qa_squad`

### ISSUE THREAD

**Issue by cstorm125** [vistec-AI/thai2transformers#21]
Sub tasks

- [x] Find sizeable dataset for benchmarking https://github.com/iapp-technology/iapp-wiki-qa-dataset
- [x] Convert to `iapp_wiki_qa_squad`: https://github.com/iapp-technology/iapp-wiki-qa-dataset
- [x] PR to huggingface/datasets: https://github.com/huggingface/datasets/pull/1873
- [x] Runnable notebook: https://colab.research.google.com/drive/1o-bM5V2C7m2BaXapwZBcavq5Ig3VF0fK?usp=sharing
- [x] Notebook that works 100% with WangchanBERTa and iapp_wiki_qa_squad (shared with @artificiala )
- [x] Train on combined iapp_wiki_qa_squad and thaiqa_squad as training set (duplicates removed)
- [x] Acceptable finetuning performance
- [x] Add helper functions to thai2transformers
- [x] Experiment scripts

**Comment by wannaphong** [comment]
@cstorm125  Try [TyDi QA](https://github.com/google-research-datasets/tydiqa)?

**Comment by cstorm125** [comment]
> @cstorm125 Try [TyDi QA](https://github.com/google-research-datasets/tydiqa)?

How many questions for Thai again?

**Comment by cstorm125** [comment]
Got it 
Train/valid/test at 11,365/2245/2203

@artificiala let's use this instead of thaiqa

**Comment by cstorm125** [comment]
TyDi QA removed thai and japanese. @kobkrit is our only hope.
https://github.com/huggingface/datasets/tree/master/datasets/tydiqa

**Comment by cstorm125** [comment]
WIP with small (4k) set of thaiqa_squad adapted from example in HF
https://colab.research.google.com/drive/1o-bM5V2C7m2BaXapwZBcavq5Ig3VF0fK?usp=sharing

**Comment by cstorm125** [comment]
Change to benchmark on this:
https://github.com/iapp-technology/iapp-wiki-qa-dataset

**Comment by cstorm125** [comment]
add `iapp_wiki_qa_squad` to huggingface/datasets
https://github.com/huggingface/datasets/pull/1873

**Comment by cstorm125** [comment]
MVP Notebook WIP at: https://colab.research.google.com/drive/1o-bM5V2C7m2BaXapwZBcavq5Ig3VF0fK?usp=sharing

**Comment by cstorm125** [comment]
Wiki models still cannot do QA because it does not provide `offset_mapping` like Fast Tokenizers.

**Comment by cstorm125** [comment]
Closing until Wikimodels can use Fast Tokenizers https://github.com/vistec-AI/thai2transformers/issues/19

**Comment by PoPae** [comment]
Hello. I used thai2transformers'project for built BERT pre-trained successed. (with run_mlm.py)
But I would like to fine-tuning in Q/A so I can't to continue with this project.
I try with "Runnable notebook: https://colab.research.google.com/drive/1o-bM5V2C7m2BaXapwZBcavq5Ig3VF0fK?usp=sharing", but failed. I'd like to get advised with fine-tuning Q/A by using BERT pre-trained model. Thank you.
