### ISSUE TITLE
tokenizers package conflicting

### ISSUE THREAD

**Issue by p4l3k1n6** [vistec-AI/thai2transformers#28]
Hi, I'm not sure this is the problem. my environment is an anaconda with python 3.7 fresh environment. I try to install your package from pip install with the command `pip install thai2transformers==0.1.0`. so I got the error 
<img width="982" alt="Screen Shot 2021-02-01 at 2 05 06 PM" src="https://user-images.githubusercontent.com/78341596/106425500-7eca6f00-6496-11eb-9f1a-5d9c228283d0.png">

thanks.

**Comment by artificiala** [comment]
Hello @p4l3k1n6,

We would like to thank for the issue you reported and sorry for the late reply. We will solve the issue and update to the next release `0.1.1` soon,

For the current release `thai2transformers==0.1.0`, the hotfix to the package conflicting issues is to install tokenizers separately with the following commend. 

```
pip install thai2transformers==0.1.0 --no-deps
pip install torch>=1.5.0 \
transformers==3.5.0 \
sentencepiece==0.1.91 \
emoji pythainlp>=2.2.4 \
tqdm datasets>=1.2.1 \
sefr_cut \
seqeval \
pytorch-lightning \
pydantic \
jsonlines \
ssg==0.0.6 \
tokenizers==0.9.3 \
pandas==1.1.4
```

**Comment by p4l3k1n6** [comment]
Hi @artificiala,

I just came to say thank you, ```pip install thai2transformers==0.1.1``` It works perfectly for me.
