### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by luangtatipsy** [vistec-AI/thai2transformers#68]
Links of data source statistics and cleaned datasets in [README](https://github.com/vistec-AI/thai2transformers#thai-texts-for-language-model-pretraining) are broken or removed. Please update the links to the latest version.

**Comment by cstorm125** [comment]
Noted with thanks. I lost the statistics with my old account. Will recompute. The cleaned datasets might only be partially available since wisesight/pantip is not under explicit open source licenses.

**Comment by lalital** [comment]
Hello @luangtatipsy,

Thanks for reporting the issue. We have uploaded the cleaned datasets used for the language model pre-training ([GitHub release](https://github.com/vistec-AI/thai2transformers/releases/tag/att-v1.0)), and added a page showing data source statistics [docs/_dataset_statistics.md](https://github.com/vistec-AI/thai2transformers/blob/master/docs/_dataset_statistics.md).

Cheers, 🎉
