### ISSUE TITLE
Incorrect filename in ./scripts/downstream

### ISSUE THREAD

**Issue by takipipo** [vistec-AI/thai2transformers#69]
According to this doc [5b_finetune_token_classificaition.md](https://github.com/vistec-AI/thai2transformers/blob/master/docs/5b_finetune_token_classificaition.md), `train_token_classificaition_lm_finetuning.py` is supposed to be `train_token_classification_lm_finetuning.py`

**Comment by lalital** [comment]
Thanks for your interested in the project and the typo correction, I have fixed it and I will merge into the master branch.
